%% S102_CreateSatGeometr: (scenario, constellation, and true GS)
%% Create the LEO constellation using walkerStar
function [sc,LeoSats,GSTrue] = S102_CreateSatGeometry(walker,startTime,stopTime,sampleTime,DevicePos)
fprintf('Creating satellite scenario...\n');
sc = satelliteScenario(startTime, stopTime, sampleTime);
fprintf('Creating LEO Walker-Star constellation...\n');
% Create satellite scenario and constellation
LeoSats = walkerStar(sc, ...
    walker.a, ...
    walker.Inc, ...
    walker.SatsPerPlane * walker.NPlanes, ...
    walker.NPlanes, ...
    walker.PhaseOffset, ...
    'Name', " ", ...
    'OrbitPropagator', 'two-body-keplerian');

%% Create the Ground-truth user
GSTrue = groundStation(sc, "Latitude", DevicePos(1), ...
                      "Longitude", DevicePos(2), ...
                      "Altitude", DevicePos(3),'Name',"Melbourne");
end